name: RyucianPlugin
main: com.spigot.Ryucian.RyucianPlugin.RyucianPlugin
version: ${project.version}
api-version: 1.16
commands:
  SummonPero:
    usage: /SummonPero
    description: test
    permission: RyucianPlugin.SummonPero
    permission-message: You don't have <permission>
    default: op
  SummonUsa:
    usage: /SummonUsa
    description: test
    permission: RyucianPlugin.SummonUsa
    permission-message: You don't have <permission>
    default: op
  ComeOnUsa:
    usage: /ComeOnUsa
    description: test
    permission: RyucianPlugin.ComeOnUsa
    permission-message: You don't have <permission>
    default: op
  GetRyucianBook:
    usage: /GetRyucianBook 
    description: test
    permission: RyucianPlugin.GetBook
    permission-message: You don't have <permission>
    default: op
 
 