name: RyucianPlugin
main: com.spigot.Ryucian.RyucianPlugin.RyucianPlugin
version: ${project.version}
api-version: 1.16
commands:
  summonpero:
    usage: /SummonPero
    description: test
    permission: Protecter.basic
    permission-message: You don't have <permission>
    default: op
 