name: RyucianPlugin
main: com.spigot.Ryucian.RyucianPlugin.RyucianPlugin
version: 0.0.1-SNAPSHOT
api-version: 1.16
commands:
  Ryucian:
    usage: /Ryucian
    description: test
    permission: Protecter.basic
    permission-message: You don't have <permission>
    default: op
 